/* SPDX-License-Identifier: Apache-2.0 */
package io.justsearch.ort;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import io.justsearch.configuration.model.ModelPrecision;
import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Base64;
import java.util.EnumSet;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

/**
 * Unit tests for the embedded-ONNX-{@code metadata_props} read rung (tempdoc 711 Item 3): a
 * build-time-stamped projection of the manifest's {@code capabilities} section, one priority rung
 * below the manifest itself.
 *
 * <p>Uses two tiny (~150-450 byte) single-node ONNX fixtures committed as base64 text under
 * {@code src/test/resources/capability-fixtures/*.onnx.b64} — generated by {@code
 * scripts/models/make_test_fixture.py}, NOT real models. {@code stamped.onnx} carries a fully
 * declared, known {@code io.justsearch.*} metadata_props set; {@code unstamped.onnx} is the
 * identical graph with zero metadata_props, for the "embedded metadata absent" case.
 */
@DisplayName("ModelCapabilityResolver — embedded ONNX metadata_props rung (tempdoc 711 Item 3)")
class ModelCapabilityResolverEmbeddedMetadataTest {

  /**
   * The embedding role's facts PLUS precision. Precision is in no role preset since tempdoc 807
   * item 2 (no production consumer reads it), but this class's subject is the embedded rung's
   * coverage of every stamped fact, so it requests precision explicitly.
   */
  private static final CapabilityRequirements EMBEDDING_PLUS_PRECISION =
      new CapabilityRequirements(
          EnumSet.of(
              CapabilityRequirements.Fact.POOLING,
              CapabilityRequirements.Fact.CONTEXT_LENGTH,
              CapabilityRequirements.Fact.DIMENSION,
              CapabilityRequirements.Fact.PRECISION,
              CapabilityRequirements.Fact.PREFIXES));

  private static Path fixturesDir;

  // Fixtures are committed as base64 TEXT resources (.onnx.b64) and materialized here at test
  // time: committing them as .onnx binaries put them under the repo-wide *.onnx LFS rule, and
  // CI checks out WITHOUT LFS blobs, so the tests received pointer files instead of ONNX
  // graphs (PR #140 first CI run).
  @BeforeAll
  static void materializeFixtures(@TempDir Path tempDir) throws IOException {
    fixturesDir = tempDir;
    for (String name : new String[] {"stamped.onnx", "unstamped.onnx"}) {
      String resource = "capability-fixtures/" + name + ".b64";
      try (InputStream in =
          ModelCapabilityResolverEmbeddedMetadataTest.class
              .getClassLoader()
              .getResourceAsStream(resource)) {
        assertNotNull(
            in,
            resource
                + " not found on classpath — run scripts/models/make_test_fixture.py and commit"
                + " its output");
        String b64 = new String(in.readAllBytes(), StandardCharsets.US_ASCII).trim();
        Files.write(fixturesDir.resolve(name), Base64.getDecoder().decode(b64));
      }
    }
  }

  @Test
  @DisplayName("embedded metadata_props resolve every fact when the manifest declares none")
  void embeddedMetadataUsedWhenManifestSilent() {
    ModelManifest manifest =
        new ModelManifest(
            "stamped.onnx", "stamped.onnx", null, null, null, ModelManifest.Capabilities.EMPTY);

    ModelCapabilities caps =
        ModelCapabilityResolver.resolve(
            "embedding", fixturesDir, manifest, EMBEDDING_PLUS_PRECISION, false);

    assertEquals(ModelCapabilities.PoolingMode.CLS, caps.poolingMode());
    assertEquals(512, caps.trainedContextLength());
    assertEquals(4, caps.embeddingDimension());
    assertEquals(ModelPrecision.FP32, caps.cpuPrecision());
    assertEquals(ModelPrecision.FP16, caps.gpuPrecision());
    assertEquals("search_document: ", caps.documentPrefix());
    assertEquals("search_query: ", caps.queryPrefix());
    assertTrue(
        caps.warnings().isEmpty(),
        "fully declared embedded metadata should produce zero warnings: " + caps.warnings());
  }

  @Test
  @DisplayName("manifest wins on disagreement with embedded metadata, and WARNs naming both values")
  void manifestWinsOnDisagreementWithEmbedded() {
    ModelManifest manifest =
        new ModelManifest(
            "stamped.onnx",
            "stamped.onnx",
            null,
            null,
            null,
            new ModelManifest.Capabilities(
                "mean", 999, 4, "fp32", "fp16", "search_document: ", "search_query: ", null));

    ModelCapabilities caps =
        ModelCapabilityResolver.resolve(
            "embedding", fixturesDir, manifest, EMBEDDING_PLUS_PRECISION, false);

    assertEquals(
        ModelCapabilities.PoolingMode.MEAN, caps.poolingMode(), "manifest value must win over embedded 'cls'");
    assertEquals(999, caps.trainedContextLength(), "manifest value must win over embedded 512");
    assertTrue(
        caps.warnings().stream()
            .anyMatch(
                w -> w.contains("pooling_mode disagreement") && w.contains("mean") && w.contains("cls")),
        "pooling_mode disagreement should name both the manifest and embedded values: "
            + caps.warnings());
    assertTrue(
        caps.warnings().stream()
            .anyMatch(
                w -> w.contains("context_length disagreement") && w.contains("999") && w.contains("512")),
        "context_length disagreement should name both the manifest and embedded values: "
            + caps.warnings());
  }

  @Test
  @DisplayName("absence of embedded metadata falls through to the existing rungs unchanged")
  void unstampedModelFallsThroughToExistingRungs() {
    ModelManifest manifest =
        new ModelManifest(
            "unstamped.onnx", null, null, null, null, ModelManifest.Capabilities.EMPTY);

    ModelCapabilities caps =
        ModelCapabilityResolver.resolve(
            "embedding", fixturesDir, manifest, EMBEDDING_PLUS_PRECISION, false);

    assertEquals(ModelCapabilities.PoolingMode.UNKNOWN, caps.poolingMode());
    assertEquals(0, caps.trainedContextLength());
    assertEquals(
        4,
        caps.embeddingDimension(),
        "boot-time graph probe (pre-existing rung, unrelated to embedded metadata_props) should"
            + " still resolve dimension from the static output shape");
    assertEquals(
        ModelPrecision.FP32,
        caps.cpuPrecision(),
        "legacy filename-substring heuristic (pre-existing rung) should still apply");
    assertNull(caps.gpuPrecision(), "no gpu variant declared");
    assertNull(caps.documentPrefix());
    assertNull(caps.queryPrefix());
    assertTrue(
        caps.warnings().stream().noneMatch(w -> w.contains("disagreement")),
        "no embedded metadata exists to disagree with: " + caps.warnings());
  }

  @Test
  void exactSelectedVariantIgnoresDifferentAndChangingAlternate(@TempDir Path modelDir)
      throws IOException {
    Path selectedCpu = Files.copy(fixturesDir.resolve("unstamped.onnx"),
        modelDir.resolve("cpu.onnx"));
    Path unselectedGpu = Files.copy(fixturesDir.resolve("stamped.onnx"),
        modelDir.resolve("gpu.onnx"));
    ModelManifest manifest = new ModelManifest("cpu.onnx", "gpu.onnx", null, null, null,
        ModelManifest.Capabilities.EMPTY);

    ModelCapabilities before = ModelCapabilityResolver.resolve("embedding", modelDir, manifest,
        EMBEDDING_PLUS_PRECISION, false, selectedCpu);
    Files.writeString(unselectedGpu, "changed-unselected-variant");
    ModelCapabilities after = ModelCapabilityResolver.resolve("embedding", modelDir, manifest,
        EMBEDDING_PLUS_PRECISION, false, selectedCpu);

    assertEquals(ModelCapabilities.PoolingMode.UNKNOWN, before.poolingMode());
    assertEquals(0, before.trainedContextLength());
    assertNull(before.documentPrefix());
    assertEquals(before, after,
        "the unselected alternate is outside the exact selected variant's authority");
  }
}
