/**
 * AUTO-GENERATED by scripts/ci/gen-component-vocabulary.mjs — DO NOT EDIT.
 *
 * The closed presentation-component vocabulary (tempdoc 569 Move 3): every host
 * jf-* custom element, i.e. the set a user-authored Presentation Declaration may
 * reference. Regenerate with `node scripts/ci/gen-component-vocabulary.mjs` after
 * adding a host element. A declaration that names a component outside this union is
 * a type error, not a silent miss.
 */

export type ComponentTag =
  | 'jf-action-button'
  | 'jf-action-ledger'
  | 'jf-activity-surface'
  | 'jf-advisory-inbox-drawer'
  | 'jf-advisory-rail-badge'
  | 'jf-advisory-toast-host'
  | 'jf-agent-activity-panel'
  | 'jf-agent-authority-panel'
  | 'jf-agent-emitter-demo'
  | 'jf-ai-activity-digest'
  | 'jf-api-explorer-view'
  | 'jf-app-update-banner'
  | 'jf-array-control'
  | 'jf-authorization-host'
  | 'jf-autonomy-dial'
  | 'jf-bookmarks-popover'
  | 'jf-boolean-control'
  | 'jf-boot-phases-panel'
  | 'jf-brain-surface'
  | 'jf-browse-surface'
  | 'jf-button'
  | 'jf-capability-map'
  | 'jf-categorization-layout'
  | 'jf-chat-shape-mount'
  | 'jf-citation-hover-card'
  | 'jf-citations-panel'
  | 'jf-command-palette'
  | 'jf-composer'
  | 'jf-confirm-dialog'
  | 'jf-context-inspector-pane'
  | 'jf-context-menu'
  | 'jf-control'
  | 'jf-conversation-history'
  | 'jf-corpus-picker'
  | 'jf-date-control'
  | 'jf-declared-surface'
  | 'jf-discrete-slider'
  | 'jf-dispatch-source'
  | 'jf-document-pane'
  | 'jf-drag-overlay'
  | 'jf-effect-audit-log'
  | 'jf-effect-line'
  | 'jf-elicit-host'
  | 'jf-engine-recovery'
  | 'jf-enter-action-picker'
  | 'jf-enum-control'
  | 'jf-error-alert'
  | 'jf-failed-jobs-drawer'
  | 'jf-filter-chip'
  | 'jf-folder-card'
  | 'jf-form'
  | 'jf-group-layout'
  | 'jf-handoff-card'
  | 'jf-health-event'
  | 'jf-health-surface'
  | 'jf-health-view'
  | 'jf-help-surface'
  | 'jf-horizontal-layout'
  | 'jf-hover-preview-host'
  | 'jf-indexing-overlay'
  | 'jf-indexing-overlay-host'
  | 'jf-ingestion-summary'
  | 'jf-interaction-retrospective-panel'
  | 'jf-library-surface'
  | 'jf-list-items'
  | 'jf-liveness-readout'
  | 'jf-log-surface'
  | 'jf-macro-dry-run'
  | 'jf-markdown-block'
  | 'jf-memory-surface'
  | 'jf-metric-card'
  | 'jf-navigate-view'
  | 'jf-navigation-receipt'
  | 'jf-number-control'
  | 'jf-object-control'
  | 'jf-op-button'
  | 'jf-operation'
  | 'jf-option-button-group'
  | 'jf-overlay-host'
  | 'jf-pane-picker'
  | 'jf-peek'
  | 'jf-pending-effect-queue'
  | 'jf-plugin-error-overlay'
  | 'jf-presentation-editor-surface'
  | 'jf-presentation-gallery-surface'
  | 'jf-provenance-badge'
  | 'jf-provenance-chip'
  | 'jf-pulse-dots'
  | 'jf-rail'
  | 'jf-reasoning-block'
  | 'jf-recents-menu'
  | 'jf-resolution-stats'
  | 'jf-resolution-toast'
  | 'jf-resource'
  | 'jf-resource-view'
  | 'jf-results-card'
  | 'jf-route-chip'
  | 'jf-row-actions'
  | 'jf-run-node'
  | 'jf-scope-chip'
  | 'jf-search-results'
  | 'jf-search-trace'
  | 'jf-security-surface'
  | 'jf-selection-actions-menu'
  | 'jf-settings-nav'
  | 'jf-settings-surface'
  | 'jf-settings-window'
  | 'jf-shell'
  | 'jf-shortcuts-table'
  | 'jf-source-chips'
  | 'jf-sources-pane'
  | 'jf-sparkline'
  | 'jf-stage'
  | 'jf-status-badge'
  | 'jf-status-card'
  | 'jf-status-deck'
  | 'jf-status-dot'
  | 'jf-summarize-view'
  | 'jf-surface-tabs'
  | 'jf-sv3-composer'
  | 'jf-sv3-context-bar'
  | 'jf-sv3-empty'
  | 'jf-sv3-main'
  | 'jf-sv3-palette'
  | 'jf-sv3-pane'
  | 'jf-sv3-session-row'
  | 'jf-sv3-sidebar'
  | 'jf-sv3-topbar'
  | 'jf-sv3-window'
  | 'jf-switch'
  | 'jf-system-notice'
  | 'jf-system-self-view'
  | 'jf-system-surface'
  | 'jf-table'
  | 'jf-task-list'
  | 'jf-text-control'
  | 'jf-time-control'
  | 'jf-timeseries-polyline'
  | 'jf-timeseries-sparkline'
  | 'jf-toggle-switch'
  | 'jf-tool-call-card'
  | 'jf-unified-chat-view'
  | 'jf-vertical-layout'
  | 'jf-walkthrough-card'
  | 'jf-x-ui-renderer-control';

export const COMPONENT_TAGS: readonly ComponentTag[] = [
  'jf-action-button',
  'jf-action-ledger',
  'jf-activity-surface',
  'jf-advisory-inbox-drawer',
  'jf-advisory-rail-badge',
  'jf-advisory-toast-host',
  'jf-agent-activity-panel',
  'jf-agent-authority-panel',
  'jf-agent-emitter-demo',
  'jf-ai-activity-digest',
  'jf-api-explorer-view',
  'jf-app-update-banner',
  'jf-array-control',
  'jf-authorization-host',
  'jf-autonomy-dial',
  'jf-bookmarks-popover',
  'jf-boolean-control',
  'jf-boot-phases-panel',
  'jf-brain-surface',
  'jf-browse-surface',
  'jf-button',
  'jf-capability-map',
  'jf-categorization-layout',
  'jf-chat-shape-mount',
  'jf-citation-hover-card',
  'jf-citations-panel',
  'jf-command-palette',
  'jf-composer',
  'jf-confirm-dialog',
  'jf-context-inspector-pane',
  'jf-context-menu',
  'jf-control',
  'jf-conversation-history',
  'jf-corpus-picker',
  'jf-date-control',
  'jf-declared-surface',
  'jf-discrete-slider',
  'jf-dispatch-source',
  'jf-document-pane',
  'jf-drag-overlay',
  'jf-effect-audit-log',
  'jf-effect-line',
  'jf-elicit-host',
  'jf-engine-recovery',
  'jf-enter-action-picker',
  'jf-enum-control',
  'jf-error-alert',
  'jf-failed-jobs-drawer',
  'jf-filter-chip',
  'jf-folder-card',
  'jf-form',
  'jf-group-layout',
  'jf-handoff-card',
  'jf-health-event',
  'jf-health-surface',
  'jf-health-view',
  'jf-help-surface',
  'jf-horizontal-layout',
  'jf-hover-preview-host',
  'jf-indexing-overlay',
  'jf-indexing-overlay-host',
  'jf-ingestion-summary',
  'jf-interaction-retrospective-panel',
  'jf-library-surface',
  'jf-list-items',
  'jf-liveness-readout',
  'jf-log-surface',
  'jf-macro-dry-run',
  'jf-markdown-block',
  'jf-memory-surface',
  'jf-metric-card',
  'jf-navigate-view',
  'jf-navigation-receipt',
  'jf-number-control',
  'jf-object-control',
  'jf-op-button',
  'jf-operation',
  'jf-option-button-group',
  'jf-overlay-host',
  'jf-pane-picker',
  'jf-peek',
  'jf-pending-effect-queue',
  'jf-plugin-error-overlay',
  'jf-presentation-editor-surface',
  'jf-presentation-gallery-surface',
  'jf-provenance-badge',
  'jf-provenance-chip',
  'jf-pulse-dots',
  'jf-rail',
  'jf-reasoning-block',
  'jf-recents-menu',
  'jf-resolution-stats',
  'jf-resolution-toast',
  'jf-resource',
  'jf-resource-view',
  'jf-results-card',
  'jf-route-chip',
  'jf-row-actions',
  'jf-run-node',
  'jf-scope-chip',
  'jf-search-results',
  'jf-search-trace',
  'jf-security-surface',
  'jf-selection-actions-menu',
  'jf-settings-nav',
  'jf-settings-surface',
  'jf-settings-window',
  'jf-shell',
  'jf-shortcuts-table',
  'jf-source-chips',
  'jf-sources-pane',
  'jf-sparkline',
  'jf-stage',
  'jf-status-badge',
  'jf-status-card',
  'jf-status-deck',
  'jf-status-dot',
  'jf-summarize-view',
  'jf-surface-tabs',
  'jf-sv3-composer',
  'jf-sv3-context-bar',
  'jf-sv3-empty',
  'jf-sv3-main',
  'jf-sv3-palette',
  'jf-sv3-pane',
  'jf-sv3-session-row',
  'jf-sv3-sidebar',
  'jf-sv3-topbar',
  'jf-sv3-window',
  'jf-switch',
  'jf-system-notice',
  'jf-system-self-view',
  'jf-system-surface',
  'jf-table',
  'jf-task-list',
  'jf-text-control',
  'jf-time-control',
  'jf-timeseries-polyline',
  'jf-timeseries-sparkline',
  'jf-toggle-switch',
  'jf-tool-call-card',
  'jf-unified-chat-view',
  'jf-vertical-layout',
  'jf-walkthrough-card',
  'jf-x-ui-renderer-control',
];

/** Type guard: is `tag` a member of the closed host component vocabulary? */
export function isComponentTag(tag: string): tag is ComponentTag {
  return (COMPONENT_TAGS as readonly string[]).includes(tag);
}

/**
 * The ATOM subset (tempdoc 574 Move 3): generic visual-atom primitives that surfaces/molecules
 * compose (a status dot, a skinned button, a status badge). A file opts in with an `@atom` header
 * marker. This is the register-coverage form (§21/P6): the single source for "what the atom tier is."
 */
export const ATOM_TAGS: readonly ComponentTag[] = [
  'jf-button',
  'jf-discrete-slider',
  'jf-error-alert',
  'jf-filter-chip',
  'jf-status-badge',
  'jf-status-dot',
  'jf-switch',
];

/** Is `tag` a registered visual atom (574 Move 3)? */
export function isAtomTag(tag: string): tag is ComponentTag {
  return (ATOM_TAGS as readonly string[]).includes(tag);
}
