/* SPDX-License-Identifier: Apache-2.0 */
package io.justsearch.agent.api.registry;

import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import java.util.Objects;

/**
 * User-confirmation strategy for an Operation invocation.
 *
 * <p>Sealed type (not enum) per tempdoc 429 §"Type-system invariants" — TYPED carries
 * the {@link I18nKey} confirmation phrase as a constructor parameter; an invalid state
 * (TYPED-without-phrase) is unrepresentable.
 *
 * <p>Jackson discriminator: {@code "kind"} field with values {@code "NONE"},
 * {@code "INLINE"}, {@code "TYPED"} per tempdoc 511-followup-2 §Track AA — the
 * discriminator name + casing aligns with the FE {@code ConfirmStrategy}
 * discriminated-union shape declared in {@code modules/ui-web/src/api/types/registry.ts}.
 * The previous {@code property = "type"} (lowercase names) was an unaligned
 * pattern from §A.3 + §E.10 that the {@code UIOperationEmitter} band-aided
 * with a manual switch; 511-followup Track E removed the band-aid, and this
 * change brings Jackson's own contract into agreement.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "kind")
@JsonSubTypes({
    @JsonSubTypes.Type(value = ConfirmStrategy.None.class, name = "NONE"),
    @JsonSubTypes.Type(value = ConfirmStrategy.Inline.class, name = "INLINE"),
    @JsonSubTypes.Type(value = ConfirmStrategy.Typed.class, name = "TYPED")
})
public sealed interface ConfirmStrategy
    permits ConfirmStrategy.None, ConfirmStrategy.Inline, ConfirmStrategy.Typed {

  /** No confirmation prompt; invoke immediately. Used for low-risk read operations. */
  record None() implements ConfirmStrategy {
    public static final None INSTANCE = new None();
  }

  /** Inline "OK to proceed?" confirmation. Used for medium-risk operations. */
  record Inline() implements ConfirmStrategy {
    public static final Inline INSTANCE = new Inline();
  }

  /**
   * Typed confirmation — the user must type the configured phrase before the operation
   * proceeds. Used for high-risk destructive operations (e.g., apply-excludes requires
   * typing "apply").
   */
  record Typed(I18nKey confirmTextKey) implements ConfirmStrategy {
    public Typed {
      Objects.requireNonNull(confirmTextKey, "confirmTextKey");
    }
  }

  /**
   * Tempdoc 564 facet 4c: a TYPED confirm whose key is derived from the operation id by the
   * {@code ops.<id-suffix>.confirm} convention — generated by construction, not hand-declared.
   */
  static Typed typedForId(NamespacedId id) {
    return new Typed(new I18nKey("ops." + id.suffix() + ".confirm"));
  }
}
