/* SPDX-License-Identifier: Apache-2.0 */
package io.justsearch.agent.api.registry;

import java.util.Objects;
import java.util.regex.Pattern;

/**
 * Sealed marker interface for namespaced primitive identifiers.
 *
 * <p>Per slice 447-followup/2.1: the framework's typed-ID records ({@link OperationRef},
 * {@link ResourceRef}, {@link PromptRef}, {@link SurfaceRef}, {@link DiagnosticChannelRef})
 * all share the same regex, validation pattern, {@code @JsonValue} serialization, and
 * {@code toString()} shape. Single-source-of-truth for the namespace pattern eliminates
 * rot risk: when the regex needs to evolve, one place updates instead of five.
 *
 * <p>This interface intentionally does NOT abstract the concrete types behind a
 * polymorphic value-class. Per impl-A §B.A.4 + 447 §X.3.2 RegistryRef rejection: there
 * are zero polymorphic call sites that take "any registry id." Each consumer of an ID
 * knows the specific primitive type (handlers register {@link OperationRef},
 * ResourceCatalog looks up {@link ResourceRef}, etc.). The interface is for
 * <strong>shape factoring</strong>, not for <strong>polymorphism</strong>.
 *
 * <p>One exception where the marker IS useful: schema-generation code that needs to
 * detect "this Java type serializes as a bare namespaced string." Before this interface,
 * three test files had {@code OperationRef.class || ResourceRef.class || PromptRef.class}
 * N-OR chains that would rot when SurfaceRef or DiagnosticChannelRef entered a tested
 * schema. With this interface, the check collapses to
 * {@code NamespacedId.class.isAssignableFrom(javaType)}.
 *
 * <p>Wire format (across all permitted variants): bare JSON string matching
 * {@link #NAMESPACE_PATTERN}. Per-record {@code @JsonValue String value()} accessors
 * deliver this shape; consumers should not depend on the marker interface for wire
 * serialization.
 */
public sealed interface NamespacedId permits RegistryRef {

  /**
   * Namespace regex shared by all permitted variants.
   *
   * <p>Format: {@code core.<id>} or {@code vendor.<vendor-id>.<id>} where
   * {@code <id>} and {@code <vendor-id>} are kebab-case lowercase. Examples:
   * {@code core.health-events}, {@code vendor.acme.metrics}.
   */
  Pattern NAMESPACE_PATTERN =
      Pattern.compile("^(core|vendor\\.[a-z][a-z0-9-]*)\\.[a-z][a-z0-9-]*$");

  /** The bare namespaced identifier value. Used for {@code @JsonValue} serialization. */
  String value();

  /**
   * The id-part after the namespace — the final dot-delimited segment ({@code core.recover-component}
   * &rarr; {@code recover-component}; {@code vendor.acme.metrics} &rarr; {@code metrics}). Per
   * {@link #NAMESPACE_PATTERN} the id-part never contains a dot, so this is the substring after the
   * last dot. Tempdoc 564 facet 4c: operation i18n keys derive from this
   * ({@code ops.<suffix>.{label,description,confirm}}), so the keys are generated by construction
   * rather than hand-declared per op.
   */
  default String suffix() {
    String v = value();
    int dot = v.lastIndexOf('.');
    return dot >= 0 ? v.substring(dot + 1) : v;
  }

  /**
   * Validates {@code value} against the shared namespace regex. Throws
   * {@code IllegalArgumentException} with a type-name-specific message on mismatch.
   * Used by each permitted record's compact constructor to enforce the shape uniformly.
   *
   * @return {@code value} for fluent assignment in record constructors.
   */
  static String validate(String value, String typeName) {
    Objects.requireNonNull(value, "value");
    if (!NAMESPACE_PATTERN.matcher(value).matches()) {
      throw new IllegalArgumentException(
          typeName
              + " must match ^(core|vendor.<x>).<id>$ (lowercase, kebab-case): "
              + value);
    }
    return value;
  }
}
