/* SPDX-License-Identifier: Apache-2.0 */
package io.justsearch.app.api;

import io.justsearch.core.context.EngineContext;
import java.util.concurrent.CompletableFuture;
import java.util.List;
import java.util.Map;
import java.util.function.Consumer;

/**
 * AI services for user-facing operations (runs via llama-server HTTP).
 *
 * <p>This interface provides streaming and non-streaming methods for:
 * <ul>
 *   <li>Summarization — generate summaries of document content</li>
 *   <li>Q&A — answer questions based on document context</li>
 * </ul>
 *
 * <p>Requires GPU in Online Mode.
 *
 * @see io.justsearch.app.services.inference.InferenceLifecycleManager
 */
public interface OnlineAiService {

  /**
   * Best-effort token usage for a single request, when the underlying runtime provides it.
   *
   * <p>Semantics follow the OpenAI-compatible `usage` object:
   * - promptTokens: tokens consumed by input messages/prompt
   * - completionTokens: tokens generated by the model
   * - totalTokens: promptTokens + completionTokens
   *
   * <p>Values may be null when unknown or unsupported by the runtime.
   */
  record AiUsage(Integer promptTokens, Integer completionTokens, Integer totalTokens) {}

  /**
   * Grouped callbacks for streaming chat completions with tool calling.
   *
   * <p>All callback types use {@code String} rather than JSON tree types to keep this API module
   * free of Jackson dependencies. Implementations bridge internally (e.g., converting parsed
   * {@code JsonNode} to {@code String} at the service boundary).
   *
   * @param onChunk callback for streamed text content chunks
   * @param onReasoningChunk callback for streamed reasoning/thinking content (separate from text)
   * @param onToolCallDelta callback for raw tool call delta JSON strings
   * @param onUsage callback for token usage (best-effort)
   * @param onComplete callback on normal completion
   * @param onError callback on error
   */
  record StreamCallbacks(
      Consumer<String> onChunk,
      Consumer<String> onReasoningChunk,
      Consumer<String> onToolCallDelta,
      Consumer<AiUsage> onUsage,
      Consumer<String> onComplete,
      Consumer<Throwable> onError) {

    /** Validates that always-invoked callbacks are non-null. */
    public StreamCallbacks {
      java.util.Objects.requireNonNull(onComplete, "onComplete");
      java.util.Objects.requireNonNull(onError, "onError");
    }

    /** Convenience factory with no-op defaults for reasoning, tools, and usage. */
    public static StreamCallbacks withDefaults(
        Consumer<String> onChunk, Consumer<String> onComplete, Consumer<Throwable> onError) {
      return new StreamCallbacks(onChunk, s -> {}, s -> {}, u -> {}, onComplete, onError);
    }
  }

  /**
   * Unified streaming request — replaces the combinatorial overload hierarchy.
   *
   * @param messages chat messages in OpenAI-style format
   * @param maxTokens max tokens to generate (<=0 uses implementation default)
   * @param tools tool definitions in OpenAI function-calling format (null = no tools)
   * @param sampling sampling parameters (null = implementation defaults)
   * @param requireSentinel when true, stream must end with [DONE] or onError fires
   */
  record StreamRequest(
      List<Map<String, Object>> messages,
      int maxTokens,
      List<Map<String, Object>> tools,
      SamplingParams sampling,
      boolean requireSentinel,
      EngineWorkHandle work) {

    /** Unattached compatibility caller; request owners pass their explicit work handle. */
    public StreamRequest(List<Map<String, Object>> messages, int maxTokens,
        List<Map<String, Object>> tools, SamplingParams sampling, boolean requireSentinel) {
      this(messages, maxTokens, tools, sampling, requireSentinel, null);
    }

    public StreamRequest(List<Map<String, Object>> messages, int maxTokens) {
      this(messages, maxTokens, null, null, true);
    }

    public StreamRequest(
        List<Map<String, Object>> messages, int maxTokens, SamplingParams sampling) {
      this(messages, maxTokens, null, sampling, true);
    }
  }

  /**
   * Multi-channel streaming sink. All LLM output channels have a slot;
   * callers that don't need a channel use the no-op default via {@link #of}.
   *
   * @param onContent text content chunks (the assistant's response)
   * @param onReasoning reasoning/thinking chunks (separate channel)
   * @param onToolCallDelta raw tool call delta JSON strings
   * @param onUsage token usage (best-effort)
   * @param onComplete normal completion (receives finish_reason)
   * @param onError error or cancellation
   */
  record StreamSink(
      Consumer<String> onContent,
      Consumer<String> onReasoning,
      Consumer<String> onToolCallDelta,
      Consumer<AiUsage> onUsage,
      Consumer<String> onComplete,
      Consumer<Throwable> onError) {

    public StreamSink {
      java.util.Objects.requireNonNull(onComplete, "onComplete");
      java.util.Objects.requireNonNull(onError, "onError");
    }

    /** Content + terminal callbacks only; reasoning, tools, usage default to no-op. */
    public static StreamSink of(
        Consumer<String> onContent, Consumer<String> onComplete, Consumer<Throwable> onError) {
      return new StreamSink(onContent, s -> {}, s -> {}, u -> {}, onComplete, onError);
    }
  }

  /** Default max tokens for summarization. */
  int DEFAULT_SUMMARY_TOKENS = 1024;

  /** Default max tokens for Q&A. */
  int DEFAULT_QA_TOKENS = 2048;

  // ==================== Streaming Methods ====================

  /**
   * Unified streaming entry point. All channels are available via {@link StreamSink}.
   *
   * <p>This is the canonical streaming method. All legacy {@code streamChat} and
   * {@code streamChatWithTools} overloads delegate to this method.
   *
   * @param request streaming request parameters
   * @param sink multi-channel output sink
   */
  default void stream(StreamRequest request, StreamSink sink) {
    sink.onError().accept(new UnsupportedOperationException("OnlineAiService.stream unsupported"));
  }

  // Tempdoc 491 §C5 (2026-05-12): streamSummary + streamAnswer (all 6 overloads) deleted.
  // They were thin pass-throughs over streamChat; their only consumers (the deleted
  // SummaryController + RagStreamingHandler + FullCoverageSummarizer + MapReducePipeline)
  // are gone. New summarize / RAG-ask shapes call streamChat directly with shape-specific
  // system prompts assembled by their PromptContributors. streamChat + streamChatWithTools
  // remain as the floor.

  // -------------------- Legacy overloads (delegate to stream()) --------------------

  /** @deprecated Use {@link #stream(StreamRequest, StreamSink)} instead. */
  default void streamChat(
      List<Map<String, Object>> messages,
      int maxTokens,
      Consumer<String> onChunk,
      Consumer<String> onComplete,
      Consumer<Throwable> onError) {
    stream(new StreamRequest(messages, maxTokens), StreamSink.of(onChunk, onComplete, onError));
  }

  /** @deprecated Use {@link #stream(StreamRequest, StreamSink)} instead. */
  default void streamChat(
      List<Map<String, Object>> messages,
      int maxTokens,
      Consumer<String> onChunk,
      Consumer<AiUsage> onUsage,
      Consumer<String> onComplete,
      Consumer<Throwable> onError) {
    stream(
        new StreamRequest(messages, maxTokens),
        new StreamSink(onChunk, s -> {}, s -> {}, onUsage, onComplete, onError));
  }

  /** @deprecated Use {@link #stream(StreamRequest, StreamSink)} instead. */
  default void streamChat(
      List<Map<String, Object>> messages,
      int maxTokens,
      Consumer<String> onChunk,
      Consumer<String> onComplete,
      Consumer<Throwable> onError,
      SamplingParams sampling) {
    stream(
        new StreamRequest(messages, maxTokens, null, sampling, true),
        StreamSink.of(onChunk, onComplete, onError));
  }

  /** @deprecated Use {@link #stream(StreamRequest, StreamSink)} instead. */
  default void streamChat(
      List<Map<String, Object>> messages,
      int maxTokens,
      Consumer<String> onChunk,
      Consumer<String> onComplete,
      Consumer<Throwable> onError,
      SamplingParams sampling,
      boolean requireSentinel) {
    stream(
        new StreamRequest(messages, maxTokens, null, sampling, requireSentinel),
        StreamSink.of(onChunk, onComplete, onError));
  }

  /** @deprecated Use {@link #stream(StreamRequest, StreamSink)} instead. */
  default void streamChatWithTools(
      List<Map<String, Object>> messages,
      List<Map<String, Object>> tools,
      int maxTokens,
      StreamCallbacks callbacks) {
    stream(
        new StreamRequest(messages, maxTokens, tools, null, true),
        new StreamSink(
            callbacks.onChunk(),
            callbacks.onReasoningChunk(),
            callbacks.onToolCallDelta(),
            callbacks.onUsage(),
            callbacks.onComplete(),
            callbacks.onError()));
  }

  /** @deprecated Use {@link #stream(StreamRequest, StreamSink)} instead. */
  default void streamChatWithTools(
      List<Map<String, Object>> messages,
      List<Map<String, Object>> tools,
      int maxTokens,
      StreamCallbacks callbacks,
      SamplingParams sampling) {
    stream(
        new StreamRequest(messages, maxTokens, tools, sampling, true),
        new StreamSink(
            callbacks.onChunk(),
            callbacks.onReasoningChunk(),
            callbacks.onToolCallDelta(),
            callbacks.onUsage(),
            callbacks.onComplete(),
            callbacks.onError()));
  }

  // ==================== Non-Streaming Methods ====================

  /**
   * Non-streaming chat completion with explicit sampling parameters. (363)
   *
   * <p>Used for structured extraction tasks (query understanding, intent classification) where the
   * full response is needed at once. Callers should set {@link SamplingParams#responseFormat()} for
   * JSON schema constraints and {@link SamplingParams#enableThinking()} to {@code false} for
   * extraction tasks.
   *
   * <p>Default implementation returns a failed future. Implementations backed by llama-server should
   * override.
   *
   * @param messages chat messages in OpenAI-style format
   * @param maxTokens max tokens to generate (<=0 uses implementation default)
   * @param sampling sampling parameters (temperature, response_format, etc.)
   * @return future containing the raw completion text (typically JSON)
   */
  default CompletableFuture<String> chatCompletion(
      List<Map<String, Object>> messages, int maxTokens, SamplingParams sampling) {
    return CompletableFuture.failedFuture(
        new UnsupportedOperationException("OnlineAiService.chatCompletion unsupported"));
  }

  /** Context-bearing non-streaming completion. Production implementations require this overload. */
  default CompletableFuture<String> chatCompletion(
      List<Map<String, Object>> messages,
      int maxTokens,
      SamplingParams sampling,
      EngineContext engineContext) {
    return chatCompletion(messages, maxTokens, sampling);
  }

  /**
   * Confidence/diagnostic signals accompanying a vision completion, alongside the extracted text.
   * Tempdoc 677 S1: plumbing only — nothing consumes these fields for gating yet.
   *
   * <p>Populated from llama-server's OpenAI-compatible response ({@code finish_reason} and,
   * when the request opted into per-token logprobs, {@code choices[0].logprobs.content[]}
   * reduced to two scalars). {@code meanLogprob} and {@code lowConfidenceFraction} are {@code
   * null} when the server did not return logprobs (not requested, or unsupported); {@code
   * tokenCount} is {@code 0} in that case.
   *
   * @param content the extracted/generated text
   * @param finishReason the OpenAI-compatible finish reason (e.g. "stop", "length"), or null if
   *     absent from the response
   * @param tokenCount number of per-token logprob entries observed (0 if none)
   * @param meanLogprob mean of per-token logprob values, or null if unavailable
   * @param lowConfidenceFraction fraction of tokens with logprob &lt; -1.0, or null if unavailable
   */
  record VisionCompletionResult(
      String content,
      String finishReason,
      int tokenCount,
      Double meanLogprob,
      Double lowConfidenceFraction) {}

  /**
   * Vision completion — extract text from an image via a multimodal model. Tempdoc 518
   * Appendix G W4.2: promoted to the role-typed interface so {@code VduProcessor} can hold
   * {@code OnlineAiService} instead of the concrete {@code InferenceLifecycleManager}.
   *
   * <p>Delegates to {@link #visionCompletionDetailed(String, byte[], int)} and returns just the
   * extracted text. Callers that need finish_reason/confidence signals should call the detailed
   * variant directly.
   *
   * @param prompt instruction prompt (e.g., "extract text from this image")
   * @param imageBytes raw image bytes (PNG/JPG)
   * @param maxTokens max tokens to generate
   * @return future containing the generated text
   */
  default CompletableFuture<String> visionCompletion(
      String prompt, byte[] imageBytes, int maxTokens) {
    return visionCompletionDetailed(prompt, imageBytes, maxTokens)
        .thenApply(VisionCompletionResult::content);
  }

  default CompletableFuture<String> visionCompletion(
      String prompt, byte[] imageBytes, int maxTokens, EngineContext engineContext) {
    return visionCompletionDetailed(prompt, imageBytes, maxTokens, SamplingParams.VDU, null,
            engineContext)
        .thenApply(VisionCompletionResult::content);
  }

  /**
   * Vision completion with finish_reason and logprob-derived confidence signals attached.
   * Tempdoc 677 S1: plumbing only, no abstention/gating behavior yet.
   *
   * <p>Delegates to {@link #visionCompletionDetailed(String, byte[], int, SamplingParams, Long)}
   * with the implementation's own vision default sampling ({@link SamplingParams#VDU} in
   * practice) and no seed override — this is the overload every VDU Pass 1 call uses.
   *
   * @param prompt instruction prompt (e.g., "extract text from this image")
   * @param imageBytes raw image bytes (PNG/JPG)
   * @param maxTokens max tokens to generate
   * @return future containing the generated text plus finish_reason/logprob-derived signals
   */
  default CompletableFuture<VisionCompletionResult> visionCompletionDetailed(
      String prompt, byte[] imageBytes, int maxTokens) {
    return visionCompletionDetailed(prompt, imageBytes, maxTokens, SamplingParams.VDU, null);
  }

  /**
   * Vision completion with an explicit sampling/seed override.
   *
   * <p>Tempdoc 677 Stage 2: the abstention gate's re-sample agreement probe uses this overload to
   * re-run Pass 1 once more at {@link SamplingParams#VDU_PROBE} (varied temperature) and a fixed
   * seed, so the probe can actually disagree with a confabulated Pass 1 output instead of
   * deterministically reproducing it. Every other caller (interactive chat, summarize, Q&amp;A,
   * VDU Pass 1 itself via the 3-arg overload, VDU Pass 2 enrichment) is untouched by this
   * overload's existence — none of them call it.
   *
   * <p>Default implementation returns a failed future. Implementations backed by a
   * vision-capable llama-server should override.
   *
   * @param prompt instruction prompt (e.g., "extract text from this image")
   * @param imageBytes raw image bytes (PNG/JPG)
   * @param maxTokens max tokens to generate
   * @param sampling sampling parameters for this call; {@code null} uses the server's own default
   * @param seed explicit RNG seed for llama-server's {@code seed} request field, or {@code null}
   *     to omit it (the server then picks its own, typically random per request)
   * @return future containing the generated text plus finish_reason/logprob-derived signals
   */
  default CompletableFuture<VisionCompletionResult> visionCompletionDetailed(
      String prompt, byte[] imageBytes, int maxTokens, SamplingParams sampling, Long seed) {
    return CompletableFuture.failedFuture(
        new UnsupportedOperationException(
            "OnlineAiService.visionCompletionDetailed unsupported"));
  }

  default CompletableFuture<VisionCompletionResult> visionCompletionDetailed(
      String prompt,
      byte[] imageBytes,
      int maxTokens,
      SamplingParams sampling,
      Long seed,
      EngineContext engineContext) {
    return visionCompletionDetailed(prompt, imageBytes, maxTokens, sampling, seed);
  }

  /**
   * Generate a summary of the content (non-streaming).
   *
   * <p>Uses {@link #DEFAULT_SUMMARY_TOKENS} as the max token limit.
   *
   * @param content text content to summarize
   * @return future containing the summary
   */
  CompletableFuture<String> summarize(String content);

  /**
   * Generate a summary with an explicit max token limit.
   *
   * <p>Default implementation ignores {@code maxTokens} and delegates to {@link #summarize(String)}.
   */
  default CompletableFuture<String> summarize(String content, int maxTokens) {
    return summarize(content);
  }

  default CompletableFuture<String> summarize(
      String content, int maxTokens, EngineContext engineContext) {
    return summarize(content, maxTokens);
  }

  /**
   * Answer a question based on context (non-streaming).
   *
   * <p>Uses {@link #DEFAULT_QA_TOKENS} as the max token limit.
   *
   * @param question user's question
   * @param context document context to query
   * @return future containing the answer
   */
  CompletableFuture<String> askQuestion(String question, String context);

  default CompletableFuture<String> askQuestion(
      String question, String context, EngineContext engineContext) {
    return askQuestion(question, context);
  }

  // ==================== Status Methods ====================

  /**
   * Check if Online Mode is available.
   *
   * @return true if llama-server is running and ready
   */
  boolean isAvailable();

  /**
   * Check if AI is currently starting up.
   *
   * @return true if transitioning to Online Mode
   */
  boolean isStartingUp();

  /**
   * Best-effort view of the actual llama-server context window (n_ctx), when available.
   *
   * <p>Returns null when unknown or when not in Online mode.
   */
  default Integer llmContextTokens() {
    return null;
  }

  /**
   * Returns the configured llama-server context window (from launch config), when known.
   */
  default Integer configuredContextTokens() {
    return null;
  }

  /**
   * Counts tokens in the given text using the llama-server /tokenize endpoint.
   *
   * <p>Returns empty if the endpoint is unavailable or the server is not in Online mode.
   * This is best-effort and should not be used for critical control flow.
   *
   * @param text the text to tokenize
   * @return the token count, or empty if unavailable
   */
  default java.util.Optional<Integer> countTokens(String text) {
    return java.util.Optional.empty();
  }

  default java.util.Optional<Integer> countTokens(String text, EngineContext engineContext) {
    return countTokens(text);
  }

  /**
   * Counts prompt tokens for OpenAI-style chat messages using llama-server's chat template.
   *
   * <p>Implementations may use llama-server's {@code /apply-template} + {@code /tokenize} endpoints.
   * Returns empty if unavailable or unsupported.
   */
  default java.util.Optional<Integer> countPromptTokens(List<Map<String, Object>> messages) {
    return java.util.Optional.empty();
  }

  /**
   * Counts prompt tokens for messages plus the tool schemas the generation call will carry.
   *
   * <p>A chat template renders tool schemas into the prompt, so counting messages alone measures a
   * prompt that will never be sent (tempdoc 878 finding 6). Pass the same {@code tools} list given
   * to the streaming call. The default delegates to {@link #countPromptTokens(List)} so an
   * implementor that only knows the schema-blind form still answers.
   */
  default java.util.Optional<Integer> countPromptTokens(
      List<Map<String, Object>> messages, List<Map<String, Object>> tools) {
    return countPromptTokens(messages);
  }

  default java.util.Optional<Integer> countPromptTokens(
      List<Map<String, Object>> messages,
      List<Map<String, Object>> tools,
      EngineContext engineContext) {
    return countPromptTokens(messages, tools);
  }

  // ==================== Mode Control Methods ====================

  /**
   * Gets the current inference mode.
   *
   * @return one of "online", "indexing", "transitioning", or "offline"
   */
  default String getCurrentMode() {
    if (isStartingUp()) return "transitioning";
    if (isAvailable()) return "online";
    return "offline";
  }

  /**
   * Attempts to switch to Online Mode.
   *
   * <p>Starts the llama-server if not running. This operation may take
   * several seconds.
   *
   * @throws UnsupportedOperationException if mode control is not available
   */
  default void switchToOnlineMode() {
    throw new UnsupportedOperationException("Mode control not available");
  }

  /**
   * Attempts to switch to Indexing Mode.
   *
   * <p>Stops the llama-server to free GPU for embedding operations.
   *
   * @throws UnsupportedOperationException if mode control is not available
   */
  default void switchToIndexingMode() {
    throw new UnsupportedOperationException("Mode control not available");
  }

  // ==================== Unavailable Implementation ====================

  /**
   * Null Object for environments where inference is not configured. Returns {@code false} from
   * {@link #isAvailable()} and safe defaults from the other interface defaults
   * ({@code getCurrentMode} → OFFLINE, {@code llmContextTokens} → null, etc.) so capability-
   * gated consumers (status endpoints, GPU saturation monitor, KnowledgeHttpApiAdapter query
   * pipeline) get a usable non-null reference before / instead of the real service.
   *
   * <p>Tempdoc 519 F2 (refined per §22): kept as the Null Object pattern. The plan's full-
   * deletion path would have scattered the unavailable-behavior across ~9 consumers; deeper
   * investigation showed several call sites (e.g., {@code InferenceHandlers.handleInferenceStatus}
   * line 67) rely on the interface default's safe return values, not just on
   * {@code isAvailable()} gating. Centralizing the no-op behavior here is the lower-cost
   * structural choice. The earlier {@code @Deprecated(forRemoval=true)} marker was removed
   * to reflect that this factory is the intended pattern, not a transitional shim.
   */
  static OnlineAiService unavailable() {
    return UnavailableOnlineAiService.INSTANCE;
  }
}

/**
 * Singleton unavailable implementation.
 */
enum UnavailableOnlineAiService implements OnlineAiService {
  INSTANCE;

  @Override
  public CompletableFuture<String> summarize(String content) {
    return CompletableFuture.failedFuture(
        new UnsupportedOperationException("OnlineAiService unavailable"));
  }

  @Override
  public CompletableFuture<String> askQuestion(String question, String context) {
    return CompletableFuture.failedFuture(
        new UnsupportedOperationException("OnlineAiService unavailable"));
  }

  @Override
  public boolean isAvailable() {
    return false;
  }

  @Override
  public boolean isStartingUp() {
    return false;
  }
}
