/**
 * Cross-language contract tests (368 RC1).
 *
 * Validates that the JSON produced by Java backend serialization conforms to
 * the frontend Zod schemas. The fixture files are generated by the Java test
 * {@code StatusRecordSchemaTest.CrossLanguageContract} in modules/app-api.
 *
 * If this test fails after a backend change:
 * 1. Run `./gradlew.bat :modules:app-api:test` to regenerate the fixture
 * 2. If the fixture shape changed intentionally, update the Zod schema to match
 * 3. If the fixture shape changed unintentionally, fix the backend
 */
import { describe, it, expect } from 'vitest';
import { settingsV2Schema } from './generated/schema-types/settings-v2';
import { statusResponseSchema } from './generated/schema-types/status-response';
import { knowledgeSearchResponseSchema } from './generated/schema-types/knowledge-search-response';
import { mapKnowledgeSearchResponse } from './domains/search';
import type { KnowledgeSearchResponse } from './domains/search';
import statusFixture from './__fixtures__/status-response-live.json';
import settingsFixture from './__fixtures__/settings-v2-live.json';
import searchFixture from './__fixtures__/search-response-live.json';

describe('Cross-language contract: StatusResponse vs generated statusResponseSchema', () => {
  it('Java-serialized StatusResponse passes Zod validation', () => {
    const result = statusResponseSchema.safeParse(statusFixture);
    if (!result.success) {
      // Print detailed error for debugging
      const issues = result.error.issues.map(
        (i) => `  ${i.path.join('.')}: ${i.message} (expected ${i.code})`,
      );
      throw new Error(
        `StatusResponse fixture failed Zod validation:\n${issues.join('\n')}`,
      );
    }
    expect(result.success).toBe(true);
  });

  it('fixture contains expected top-level fields', () => {
    const data = statusFixture as Record<string, unknown>;
    // Head-level fields
    expect(data).toHaveProperty('schema_version');
    expect(data).toHaveProperty('lifecycle');
    expect(data).toHaveProperty('components');
    expect(data).toHaveProperty('status');
    expect(data).toHaveProperty('uptimeMs');

    // 384: Worker data nested under "worker" key
    expect(data).toHaveProperty('worker');
    const worker = data.worker as Record<string, unknown>;
    expect(worker).toHaveProperty('core');
    expect(worker).toHaveProperty('failure');
    expect(worker).toHaveProperty('searchConfig');

    // Grouped sub-objects (330 section 4)
    expect(data).toHaveProperty('embedding');
    expect(data).toHaveProperty('schema');
    expect(data).toHaveProperty('chunkCoverage');
    expect(data).toHaveProperty('queueHealth');
    expect(data).toHaveProperty('migration');

    // Nested views — Tempdoc 412 Phase 3: llm + onlineAi replaced by inference.
    expect(data).toHaveProperty('inference');
    expect(data).toHaveProperty('readiness');
    expect(data).toHaveProperty('meta');
  });

  it('readiness envelope has expected structure', () => {
    const data = statusFixture as Record<string, unknown>;
    const readiness = data.readiness as Record<string, unknown>;
    expect(readiness.schemaVersion).toBe(2);
    const engines = readiness.engineComponents as Record<string, { state: string; stateSince: string }>;
    expect(Object.keys(engines).sort()).toEqual(['api', 'encoders', 'generative', 'index']);
    expect(engines.index?.state).toBe('READY');
    expect(engines.index?.stateSince).toBe('2025-01-01T00:00:00Z');
    expect(readiness).toHaveProperty('observedAt');
    expect(readiness).toHaveProperty('components');
    expect(readiness).toHaveProperty('composites');
  });
});

describe('Cross-language contract: SettingsV2 round-trip', () => {
  // Tempdoc 683 (X3): validates against the GENERATED strict `settingsV2Schema`
  // (record → JSON Schema → Zod), not the retired fail-open `.loose()` hand schema —
  // an unknown wire key now fails here instead of passing silently.
  it('Java-serialized SettingsV2 passes generated Zod validation', () => {
    const result = settingsV2Schema.safeParse(settingsFixture);
    if (!result.success) {
      const issues = result.error.issues.map(
        (i) => `  ${i.path.join('.')}: ${i.message} (expected ${i.code})`,
      );
      throw new Error(
        `SettingsV2 fixture failed Zod validation:\n${issues.join('\n')}`,
      );
    }
    expect(result.success).toBe(true);
  });

  it('fixture contains all expected settings fields', () => {
    const data = settingsFixture as Record<string, unknown>;
    expect(data).toHaveProperty('ui');
    expect(data).toHaveProperty('llm');
    expect(data).toHaveProperty('indexPaths');
    expect(data).toHaveProperty('settingsMode');
    expect(data.settingsMode).toMatch(/^(read_write|in_memory)$/);

    const ui = data.ui as Record<string, unknown>;
    expect(ui).toHaveProperty('theme');
    expect(ui).toHaveProperty('highContrast');
    expect(ui).toHaveProperty('density');
    expect(ui).toHaveProperty('vimMode');
    expect(ui).toHaveProperty('defaultAction');
    expect(ui).toHaveProperty('inspectorWidth');
    expect(ui).toHaveProperty('mode');
    expect(ui).toHaveProperty('excludePatterns');
  });
});

describe('Cross-language contract: KnowledgeSearchResponse → generated knowledgeSearchResponseSchema', () => {
  it('Java-serialized search response passes generated Zod validation, then maps', () => {
    // Tempdoc 683: the hand SearchResponseSchema (fail-open post-map check) is deleted. This
    // tests the actual production flow: raw → parseWireContract(generated) → map. The raw
    // fixture must pass the generated strict schema, and the mapper must accept the parsed data.
    const result = knowledgeSearchResponseSchema.safeParse(searchFixture);
    if (!result.success) {
      const issues = result.error.issues.map(
        (i) => `  ${i.path.join('.')}: ${i.message} (expected ${i.code})`,
      );
      throw new Error(
        `Raw search response fixture failed generated Zod validation:\n${issues.join('\n')}`,
      );
    }
    expect(result.success).toBe(true);
    const mapped = mapKnowledgeSearchResponse(result.data as KnowledgeSearchResponse);
    expect(mapped.hits.length).toBeGreaterThan(0);
  });

  it('mapped response preserves hit data', () => {
    const mapped = mapKnowledgeSearchResponse(searchFixture as unknown as KnowledgeSearchResponse);
    expect(mapped.totalHits).toBe(2);
    expect(mapped.hits).toHaveLength(2);
    const hit = mapped.hits[0]!;
    expect(hit.title).toBe('System Architecture');
    expect(hit.path).toBe('C:/docs/architecture.md');
    expect(hit.score).toBeCloseTo(0.95);
    expect(hit.matchedFields).toContain('title');
  });

  // Tempdoc 549 Phase E2/E3: per-hit provenance + pipelineExecution retired — per-hit ranking
  // and per-stage timing/status are now on the unified searchTrace.

  it('mapped response preserves metadata fields (364 T1-C)', () => {
    const mapped = mapKnowledgeSearchResponse(searchFixture as unknown as KnowledgeSearchResponse);
    expect(mapped.hits[0]!.metaSource).toBe('documentation');
    expect(mapped.hits[0]!.metaAuthor).toBe('engineering');
  });

  it('raw fixture has expected wire format fields', () => {
    const data = searchFixture as Record<string, unknown>;
    expect(data).toHaveProperty('totalHits');
    expect(data).toHaveProperty('tookMs');
    expect(data).toHaveProperty('results');
    expect(data).toHaveProperty('facets');
    expect(data).toHaveProperty('indexCapabilities');
    expect(data).toHaveProperty('entityFacetVariants');
  });
});

// ==================== 380: Mapper propagation test ====================

describe('380: Mapper propagation — no silent field drops', () => {
  // Mapping from Lucene field names (snake_case in fields map) to camelCase SearchHit properties.
  // This is the single source of truth for the snake→camel rename in the mapper.
  // Mapping from Lucene field names (snake_case in the fields map) to camelCase
  // SearchHit properties. Only includes fields that map 1:1 from the fields map
  // to a SearchHit property. Excludes `filename` (consumed internally for title
  // derivation, never a SearchHit field) and `doc_id` (carried as top-level Hit.id).
  const FIELD_RENAME_MAP: Record<string, string> = {
    collection: 'collection',
    content_preview: 'contentPreview',
    file_kind: 'fileKind',
    language: 'language',
    meta_author: 'metaAuthor',
    meta_category: 'metaCategory',
    meta_published_at: 'metaPublishedAt',
    meta_source: 'metaSource',
    mime: 'mime',
    mime_base: 'mimeBase',
    modified_at: 'modifiedAt',
    path: 'path',
    size_bytes: 'sizeBytes',
    title: 'title',
  };

  // Top-level result properties (not from fields map) that should propagate.
  // Tempdoc 549 Phase E2: provenance retired from the SearchHit mapping (per-hit ranking is the trace slice).
  const TOP_LEVEL_PROPS = ['excerptRegions', 'matchedFields', 'matchSpans'] as const;

  it('all fields map entries from rich fixture hit propagate to mapped SearchHit', () => {
    const mapped = mapKnowledgeSearchResponse(searchFixture as unknown as KnowledgeSearchResponse);
    const hit = mapped.hits[0]! as unknown as Record<string, unknown>;
    const rawFields = ((searchFixture as any).results[0].fields || {}) as Record<string, unknown>;

    for (const [luceneKey, camelKey] of Object.entries(FIELD_RENAME_MAP)) {
      if (luceneKey in rawFields) {
        expect(hit[camelKey], `fields.${luceneKey} → SearchHit.${camelKey} should be defined`).toBeDefined();
      }
    }
  });

  it('sparse hit (missing optional fields) maps without crashing', () => {
    const mapped = mapKnowledgeSearchResponse(searchFixture as unknown as KnowledgeSearchResponse);
    const sparse = mapped.hits[1];
    expect(sparse).toBeDefined();
    expect(sparse!.title).toBeDefined();
    expect(sparse!.path).toBeDefined();
    // Optional fields should be undefined, not throw
    expect(sparse!.excerptRegions).toBeUndefined();
    expect(sparse!.matchSpans).toBeUndefined();
    expect(sparse!.contentPreview).toBeUndefined();
  });

  it('top-level result properties propagate when present', () => {
    const mapped = mapKnowledgeSearchResponse(searchFixture as unknown as KnowledgeSearchResponse);
    const hit = mapped.hits[0]! as unknown as Record<string, unknown>;
    const rawHit = (searchFixture as any).results[0] as Record<string, unknown>;

    for (const prop of TOP_LEVEL_PROPS) {
      if (rawHit[prop] != null) {
        expect(hit[prop], `result.${prop} → SearchHit.${prop} should be defined`).toBeDefined();
      }
    }
  });
});

// Tempdoc 564 Phase A: the "Zod covers all JSON Schema properties" test was retired — the status
// Zod is now GENERATED from the JSON Schema (statusResponseSchema), so coverage is tautological by
// construction (the prior hand SystemStatusSchema could drift; the generated one cannot). The
// modelDistribution drift the old allowlist tracked is auto-resolved (it's in the generated Zod).
