"""Fixture bodies must satisfy the wire schema the FE parse boundary validates against.

Tempdoc 911 (885 UL.10). `test_ui_fixtures.py` already pinned "the non-fail-open parse boundary
needs schema-valid bodies" — but it pinned a HAND-PICKED set of keys, so it could not notice when
the schema grew. That is exactly what happened: tempdoc 884 moved
`SurfaceCatalogClient.tryFetchAndPopulate` onto the generated `z.strictObject` for
`/api/registry/surfaces`, which requires eleven properties; `_surface_entry` supplied seven and
omitted `members` when empty. The fetch then failed inside a `catch` on every retry, the catalog
never carried `members`, the member->host redirect could not resolve, and the `security` /
`security-light` a11y-gate steps timed out waiting for the settings modal — for months, silently.

So this asserts the fixture against the SCHEMA rather than against a remembered key list: it grows
when the record grows, which the hand-picked version could not.

Honest limit: JSON Schema here checks REQUIRED-ness and types, not unknown keys — the generated Zod
is `z.strictObject` but `surface.v1.json` carries no `additionalProperties: false`, so an extra key
would pass here and fail in the browser. Missing-required is the failure that actually bit, and it
is the one this catches.
"""
from __future__ import annotations

import json
from pathlib import Path

import pytest

from jseval import ui_fixtures

jsonschema = pytest.importorskip("jsonschema", reason="jseval[dev] extra")


def _repo_root() -> Path:
    cursor = Path(__file__).resolve()
    for parent in cursor.parents:
        if (parent / "SSOT" / "schemas").is_dir():
            return parent
    raise AssertionError("could not locate the repo root (no SSOT/schemas above this file)")


def _surface_schema() -> dict:
    path = _repo_root() / "SSOT" / "schemas" / "surface.v1.json"
    assert path.is_file(), f"{path} must exist (generated by SurfaceSchemaGenTest)"
    return json.loads(path.read_text(encoding="utf-8"))


class TestSurfaceCatalogFixtureConformsToWireSchema:
    def test_every_entry_validates(self):
        schema = _surface_schema()
        body = json.loads(ui_fixtures.fixture_body("http://x/api/registry/surfaces"))
        entries = body.get("entries")
        assert isinstance(entries, list) and entries, "the surfaces fixture must carry entries"

        validator = jsonschema.Draft202012Validator(schema)
        for entry in entries:
            errors = sorted(validator.iter_errors(entry), key=lambda e: e.json_path)
            assert not errors, (
                f"surface fixture entry {entry.get('id')!r} does not satisfy "
                f"SSOT/schemas/surface.v1.json: "
                + "; ".join(f"{e.json_path}: {e.message}" for e in errors)
            )

    def test_members_is_always_present(self):
        # The specific omission that broke the redirect: `members` was added only `if members:`,
        # so every non-host entry lacked it. It is a required property with no default — a
        # host/member relationship the FE cannot see is a redirect the FE cannot make.
        body = json.loads(ui_fixtures.fixture_body("http://x/api/registry/surfaces"))
        for entry in body["entries"]:
            assert "members" in entry, f"{entry.get('id')!r} omits the required `members`"

    def test_the_settings_host_still_declares_the_security_member(self):
        # The one relationship the security/security-light a11y-gate steps depend on. Asserted here
        # too, because a schema-valid catalog that lost this edge would pass the test above.
        body = json.loads(ui_fixtures.fixture_body("http://x/api/registry/surfaces"))
        hosts = {e["id"]: e.get("members", []) for e in body["entries"]}
        assert "core.security-surface" in hosts.get("core.settings-surface", []), (
            "core.settings-surface must host core.security-surface, or the member->host redirect "
            "the `security` ui-shot step relies on cannot resolve"
        )


class TestInstallPreviewScenario:
    def test_uninstalled_status_satisfies_the_real_wire_schema(self):
        schema = json.loads((_repo_root() / "SSOT/schemas/ai-install-status.v1.json").read_text(encoding="utf-8"))
        body = json.loads(ui_fixtures.fixture_body("http://x/api/ai/install/status", "install-preview"))
        jsonschema.Draft202012Validator(schema).validate(body)
        assert body["state"] == "idle" and body["installedFully"] is False
        status = json.loads(ui_fixtures.fixture_body("http://x/api/status", "install-preview"))
        assert status["inference"]["engineState"] == "Down"
        assert status["inference"]["identity"] is None
        assert status["inference"]["chatEnabledSpec"] is False
        assert status["aiReady"] is False
        ordinary = json.loads(ui_fixtures.fixture_body("http://x/api/status"))
        assert ordinary["inference"]["engineState"] == "Healthy"

    def test_component_rows_and_consent_terms_share_the_registry_source(self):
        manifest = json.loads(ui_fixtures.fixture_body("http://x/api/ai/install/manifest", "install-preview"))
        preview = json.loads(ui_fixtures.fixture_body("http://x/api/ai/install/plan-preview", "install-preview"))
        packages = {p["id"]: p for p in manifest["packages"]}
        assert set(packages) == {"embedding", "reranker"}
        assert {c["necessity"] for c in preview["components"]} == {"required", "improves-results"}
        for component in preview["components"]:
            package = packages[component["id"]]
            assert component["label"] == package["label"]
            assert package["license"] and package["termsUrl"]
            assert component["state"] == "to-download"
            assert component["downloadBytes"] == component["totalBytes"] > 0
        assert preview["totalDownloadBytes"] == sum(c["downloadBytes"] for c in preview["components"])
        assert {tier["tier"]: tier["label"] for tier in preview["tiers"]} == {
            "retrieval-core": "Core retrieval", "retrieval-enrichment": "Retrieval enrichment",
        }
        assert json.loads(ui_fixtures.fixture_body("http://x/api/ai/install/plan-preview")) == {}
